### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by joeyeng** [JamesRandall/FunctionMonkey#1]
Hey James, I followed your blog post to setup a simple REST API, but getting this error when compiling: 

MSB3073 The command "dotnet "C:\Users\engj\.nuget\packages\compilecommandingfunctions\0.2.0-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.0/CompileCommandingFunctions.dll" C:\Users\engj\source\repos\Experimental\FunctionApp1\bin\Debug\netstandard2.0\bin\FunctionApp1.dll C:\Users\engj\source\repos\Experimental\FunctionApp1\bin\Debug\netstandard2.0\" exited with code -532462766.FunctionApp1C:\Users\engj\.nuget\packages\compilecommandingfunctions\0.2.0-beta000\build\netstandard1.0\CompileCommandingFunctions.targets9

Any ideas?

![image](https://user-images.githubusercontent.com/8000546/40189074-570076b6-59b0-11e8-8045-383a4bd87da1.png)

**Comment by JamesRandall** [comment]
I need to update the blog post (I'll do that now!) - I've renamed it and made quite a few changes and fixes since then. The packages to add are now FunctionMonkey and FunctionMonkey.Compiler.

I've updated the sample that mirrors the blog post here: https://github.com/JamesRandall/AzureFunctionsSimpleRestApiExample

Would be very interested to know if you have that issue with that sample and the latest packages. The hairiest bit of this is the MSBuild target stuff - and packaging MSBuild tasks as NuGet packages is pretty new to me.

It "works on my machine" but I suspect might need some further work.

**Comment by giemch** [comment]
Okay, thanks! I'll give that a shot.

**Comment by giemch** [comment]
Okay, I cloned your example and it works! I tried making the changes to my existing test function and it's still complaining. Everything looks identical, so I'm not sure why. I put it up on github if you wanna take a look. https://github.com/giemch/FunctionApp1

**Comment by JamesRandall** [comment]
Great - thanks for that, I'll clone it and take a look this evening. Really appreciated.

**Comment by JamesRandall** [comment]
Got to the bottom of it - its because the BlogPost model is internal. Models and commands need to be public for the compiled function app to see them. It's not normally an issue if you structure a commanding solution as I normally would (separate assemblies for commands and handlers) but is here.

At a minimum I'll make this kick out a sensible error message so will leave this open for now.

Thanks so much for trying this and taking the time to give me the feedback and the source. Really appreciated!

**Comment by giemch** [comment]
Got it. Thanks, James!

**Comment by JamesRandall** [comment]
The next release to Nuget (> 0.8.1) contains an update for this that lists out commands and repsonses that are not public so hopefully will be a bit more obvious. Thanks for the feedback :)
