### ISSUE TITLE
FunctionMonkey.Compiler build error

### ISSUE THREAD

**Issue by indulismisins** [JamesRandall/FunctionMonkey#103]
Hi,

I followed your Video series and created new Azure function with latest FunctionMonkey package versions. On build I get this error:

Error MSB3073: The command "dotnet "C:\Users\by274\.nuget\packages\functionmonkey.compiler\3.0.17\build\netstandard1.0\..\..\tools\netcoreapp2.1/FunctionMonkey.Compiler.dll" "C:\Users\by274\source\repos\import-as-a-service\ImportAsAService\Workflow\bin\Debug\netstandard2.0\bin\Workflow.dll"" exited with code -532462766. (1, 1)

**Comment by JamesRandall** [comment]
I've improved the error logging in the v4 beta (now available on NuGet) for .NET Core 3.1 - could you give that a go please?

**Comment by mdg215199** [comment]
If you are using Visual Studio, be sure you have >= 16.4.  Also, if trying to troubleshoot by using the v4 beta, if you set both:
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>

You might have issues due to this bug as well:
https://github.com/Azure/azure-functions-host/issues/5145

The last couple comments resolve, though, if you download the specific zip file to have the right azurefunctiontools, be sure to pay attention as matteotumiati mentions, as the manifest that was given in that zip file wont match your user, which will then give more errors.

**Comment by JamesRandall** [comment]
This should be resolved in the latest beta: v4.0.44-beta.4
