### ISSUE TITLE
Replace Newtonsoft.Json with new System.Text.Json Api's 

### ISSUE THREAD

**Issue by MrBliz** [JamesRandall/FunctionMonkey#104]
As per this tweet.

https://twitter.com/AzureTrenches/status/1206627061273649153?s=20

I Should have a PR for you by the weekend.

**Comment by mdg215199** [comment]
I would hold on doing this (or at least give the option of continue using newtonsoft). 
 Main reason I say this, this was a huge issue for my development: https://github.com/dotnet/corefx/issues/38579

I was excited to use System.text.json, but I ended up having to pull out due to the issues in that ticket.

**Comment by JamesRandall** [comment]
I've also run into issues with not being able to instruct it to ignore properties, will close this for now and can look at it again when System.Text.Json is more mature.
