### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by nugosu** [JamesRandall/FunctionMonkey#26]
I have been attempting to work with entity frameworks cosmos provider and function monkey.

1>------ Build started: Project: Tutorial, Configuration: Debug Any CPU ------
1>Tutorial -> C:\GIT\myAzureFunction\FunctionMonkey\Tutorial\bin\Debug\netcoreapp2.1\bin\Tutorial.dll
1>
1>Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>   at Tutorial.ServerlessBlogConfiguration.Build(IFunctionHostBuilder builder)
1>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in C:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 73
1>   at FunctionMonkey.Compiler.Program.Main(String[] args) in C:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 47
1>C:\Users\melgs\.nuget\packages\functionmonkey.compiler\0.18.6-beta000\build\netstandard1.0\FunctionMonkey.Compiler.targets(19,5): error MSB3073: The command "dotnet "C:\Users\melgs\.nuget\packages\functionmonkey.compiler\0.18.6-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.1/FunctionMonkey.Compiler.dll" "C:\GIT\myAzureFunction\FunctionMonkey\Tutorial\bin\Debug\netcoreapp2.1\bin\Tutorial.dll" --netcore21" exited with code -532462766.
1>Done building project "Tutorial.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by wynandjordaan** [comment]
Hi there,

I had similar issues, the problem is you are using a newer version of the Microsoft.Extensions.DependencyInjection.Abstractions (Version=2.2.0.0) and internally in the Function Monkey compiler it uses version 2.0 I think. 

So one workaround is to downgrade your package to also use version 2.0.

You can find the exact version that the compiler is using in the folder: C:\Users\melgs.nuget\packages\functionmonkey.compiler\0.18.6-beta000\tools\netcoreapp2.1

**Comment by nugosu** [comment]
Thank you.
